import { expect, test } from '@playwright/test'

test('color stops drag on the rail and support precise keyboard movement', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Use Dusk preset' }).click()
  const handle = page.getByRole('slider', { name: 'Color stop 2 position' })
  const box = (await handle.boundingBox())!
  const rail = (await page.locator('.gradient-rail').boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(rail.x + rail.width * .75, box.y + box.height / 2, { steps: 8 })
  await expect(handle).toHaveAttribute('aria-valuenow', '75')
  await expect(page.getByLabel('Selected stop position')).toHaveValue('75')
  await expect(page.getByTestId('css-output')).toContainText('#C85B72 75%')
  await page.mouse.move(rail.x + rail.width + 100, box.y + box.height / 2)
  await expect(handle).toHaveAttribute('aria-valuenow', '100')
  await page.mouse.move(rail.x - 100, box.y + box.height / 2)
  await expect(handle).toHaveAttribute('aria-valuenow', '0')
  await page.mouse.up()
  await handle.press('ArrowRight')
  await expect(handle).toHaveAttribute('aria-valuenow', '1')
  await handle.press('Shift+ArrowRight')
  await expect(handle).toHaveAttribute('aria-valuenow', '11')
  await handle.press('End')
  await expect(handle).toHaveAttribute('aria-valuenow', '100')
  await handle.press('Home')
  await expect(handle).toHaveAttribute('aria-valuenow', '0')
})

test('edits a gradient, moves text, fixes contrast, and exposes CSS', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Gradient' })).toBeVisible()

  await page.getByLabel('Gradient angle').fill('32')
  await page.getByLabel('Text color picker').fill('#C85B72')
  await expect(page.getByText('Estimated AA fail')).toBeVisible()

  const previewText = page.getByTestId('preview-text')
  await previewText.focus()
  await previewText.press('ArrowRight')
  await previewText.press('ArrowDown')

  await page.getByRole('button', { name: 'Make readable' }).click()
  await expect(page.getByText('Estimated AA pass')).toBeVisible()
  await expect(page.getByTestId('css-output')).toContainText('.gradient-hero')
  await expect(page.getByTestId('css-output')).toContainText('linear-gradient(32deg')
})

test('mobile editing keeps the canvas visible and resamples after resizing', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto('/')
  await page.getByRole('tab', { name: 'controls' }).click()
  await expect(page.getByTestId('preview-frame')).toBeVisible()
  await page.getByRole('button', { name: 'Use Dune preset' }).click()
  await page.getByRole('textbox', { name: 'Content', exact: true }).fill('Readable everywhere')
  await expect(page.getByTestId('preview-text')).toHaveText('Readable everywhere')
  await page.getByRole('tab', { name: 'results' }).click()
  await expect(page.getByText('Estimated AA fail')).toBeVisible()
  await page.getByRole('button', { name: 'Make readable' }).click()
  await expect(page.getByText('Estimated AA pass')).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByText('Estimated AA fail')).toBeVisible()
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(page.getByText('Estimated AA pass')).toBeVisible()
  await page.getByRole('button', { name: 'Share configuration' }).click()
  await expect(page).toHaveURL(/state=/)
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export CSS file' }).click()
  expect((await download).suggestedFilename()).toBe('gradient-guard.css')
  await page.setViewportSize({ width: 1024, height: 768 })
  await expect.poll(() => page.locator('canvas').evaluate((canvas: HTMLCanvasElement) =>
    Math.abs(canvas.width - Math.round(canvas.getBoundingClientRect().width * devicePixelRatio)),
  )).toBeLessThanOrEqual(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(page.getByTestId('preview-text')).toHaveText('Readable everywhere')
})
